package seed

import (
	"github.com/bookpanda/mygraderlist-backend/src/app/model/problem"
)

var problems = []problem.Problem{
	{
		CourseCode: "2110211",
		Group:      "ex",
		Code:       "ex00e1",
		Name:       "Time After",
	},
	{
		CourseCode: "2110211",
		Group:      "ex",
		Code:       "ex00e2",
		Name:       "Min Max",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds00_reverse",
		Name:       "Reverse Vector 1",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q0_remove_even",
		Name:       "Remove Even",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q1c_vector_op",
		Name:       "Vector Operation",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q1a_punch",
		Name:       "Vector Punch",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds01_pair_sum",
		Name:       "Pair Sum",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds00_reverse2",
		Name:       "Reverse Vector 2",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q0_vector_swap",
		Name:       "Vector Swap",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds02_intersection",
		Name:       "Intersection",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds01_most",
		Name:       "Most Frequent Word",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q1c_vector_intersection",
		Name:       "Vector Intersection",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q1b_grandfather",
		Name:       "Grandfather",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q1a_vote",
		Name:       "Vote",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q0_rating",
		Name:       "CUCAS Rating",
	},
	{
		CourseCode: "2110211",
		Group:      "ex",
		Code:       "ex00e3",
		Name:       "Check Mapping",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q1b_interval_count",
		Name:       "Interval Count",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q0_histogram",
		Name:       "Histogram",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_qx_inside_interval",
		Name:       "Inside Interval",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q1a_hiatus",
		Name:       "Hiatus",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q0_v2m",
		Name:       "Vector to Map",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q1a_multiply",
		Name:       "Member Multiply",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q1a_card_battle",
		Name:       "Card Battle",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q1b_list_erase",
		Name:       "Vector List Erase",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q1a_multi_insert",
		Name:       "Multi Insert",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q1b_password",
		Name:       "Password",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q1b_moving_median",
		Name:       "Moving Median",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q1a_second_min",
		Name:       "Second Min",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q0_stack_concat",
		Name:       "Stack Concatenate",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q1_postfix",
		Name:       "Evaluate Postfix",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q1a_delivery",
		Name:       "Food Delivery",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q1b_queue_count",
		Name:       "Queue Count",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q0_zipcode",
		Name:       "Zipcode",
	},
	{
		CourseCode: "2110211",
		Group:      "ex",
		Code:       "ex00m2",
		Name:       "Auction",
	},
	{
		CourseCode: "2110211",
		Group:      "ex",
		Code:       "ex00m1",
		Name:       "Restaurant",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q1c_min_of_max",
		Name:       "Min of Max",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q1c_ice_cream",
		Name:       "Ice Cream",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q1b_cross_2d",
		Name:       "3: Cross 2D",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q1b_sparse_vector",
		Name:       "4: Sparse Vector",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q2a_pair_gte",
		Name:       "Pair GTE",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q1a_topsale",
		Name:       "Top Sale",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q1a_booking",
		Name:       "Booking",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds02_is_reverse",
		Name:       "Is Reverse?",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q2a_no_move",
		Name:       "2: Vector No Move",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q2a_vector_mirror",
		Name:       "Vector Mirror",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q2c_wasted_space",
		Name:       "Wasted Space",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q2a_iterator_check",
		Name:       "Iterator Check",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q1_erase_many",
		Name:       "Erase Many from Vector",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q1_vequal",
		Name:       "Vector Equality",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q2b_vector_compress",
		Name:       "Vector Compress",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q2c_vector_swap",
		Name:       "Swap Vector",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q2b_vector_insert_many",
		Name:       "Insert Many",
	},
	{
		CourseCode: "2110211",
		Group:      "d61",
		Code:       "d61_q1_ordered_set",
		Name:       "Ordered Set",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q1_v_uniq",
		Name:       "Vector Unique",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q1_range_insert",
		Name:       "Range Insert",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q2c_vector_less",
		Name:       "Vector less",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q2b_vector_rotate",
		Name:       "Vector Rotate",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q2a_vector_block_swap",
		Name:       "Vector Block Swap",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q2b_some_move",
		Name:       "Vector Some Move",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q2b_stack_reserve",
		Name:       "Stack Reserve Compare",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q2b_stack_deep_push",
		Name:       "Stack Deep Push",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q1_pop_many",
		Name:       "Pop Many",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q2b_stack_distribute",
		Name:       "Stack Distribute",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q1_sbv2",
		Name:       "Stack by Vector 2",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q1_sbv",
		Name:       "Stack by Vector",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q2a_mitosis",
		Name:       "1: Stack Mitosis",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q2c_stack_move_insert",
		Name:       "Move Insert Stack",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q2a_stack_from_set",
		Name:       "Stack From Set",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q3a_queue_check",
		Name:       "Queue Check",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q3b_queue_b2f",
		Name:       "Queue Back to Front",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q3a_queue_m2b",
		Name:       "Queue Move to Back",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q3b_queue_m2f",
		Name:       "Queue Move to Front",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q2a_multi_count",
		Name:       "Multi Count",
	},
	{
		CourseCode: "2110211",
		Group:      "d61",
		Code:       "d61_q1_append",
		Name:       "Append",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q2_split_queue",
		Name:       "Split Queue",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q1_qat",
		Name:       "Queue At",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q2_queue_equality",
		Name:       "Queue Equality",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q1_to_vector",
		Name:       "Queue to Vector",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q3b_queue_total_reverse",
		Name:       "Queue Total Reverse",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q3a_queue_min",
		Name:       "Queue Min Element",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q2b_split_stack",
		Name:       "Split Stack",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q3b_queue_reverse",
		Name:       "Queue Reverse",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_03_01",
		Name:       "Digital: Simulation 03 - 01",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_01_01",
		Name:       "Digital: Simulation 01 - 01",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q2a_vector_range_erase",
		Name:       "Vector Range Erase",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q2a_stack_vertical_split",
		Name:       "Stack Vertical Split",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q1b_car_brake",
		Name:       "Car Brake",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q3b_kheap_height",
		Name:       "K-ary Heap Height",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q3a_heap_node_relation",
		Name:       "Heap Node Relation",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q2_heap_height",
		Name:       "Heap Height",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q2_kheap",
		Name:       "K-Ary Heap",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds03_heap_erase",
		Name:       "Heap Erase",
	},
	{
		CourseCode: "2110211",
		Group:      "d62",
		Code:       "d62_q3a_heap_descendant",
		Name:       "Heap Descendant",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q2_heap_find",
		Name:       "Heap Find",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q2_hequal",
		Name:       "Heap Equality",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds03_heap_order",
		Name:       "Heap Ordering",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q2_custom",
		Name:       "Custom Order",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q2_heap_order2",
		Name:       "Heap Ordering 2",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q3a_heap_relation_2",
		Name:       "Heap Node Relation 2",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q3b_heap_change",
		Name:       "Heap Change Value",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q3a_rank_in_heap",
		Name:       "Rank in Heap",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q3b_heap_check",
		Name:       "Heap Check",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q3b_heap_level",
		Name:       "Heap Level",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q3a_heap_kth",
		Name:       "Heap K-th",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_07_05",
		Name:       "Digital: Simulation 07 - 05",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_07_04",
		Name:       "Digital: Simulation 07 - 04",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_07_03",
		Name:       "Digital: Simulation 07 - 03",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_07_02",
		Name:       "Digital: Simulation 07 - 02",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_07_01",
		Name:       "Digital: Simulation 07 - 01",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q4a_list_reverse",
		Name:       "List Reverse",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q3_list_replace",
		Name:       "List Replace",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q3_zuma",
		Name:       "Zuma",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q4a_list_merge",
		Name:       "List Merge",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q4b_list_extract",
		Name:       "List Extract",
	},
	{
		CourseCode: "2110211",
		Group:      "d61",
		Code:       "d61_q2_splitlist",
		Name:       "Split List",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q3_list_split",
		Name:       "List Split",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds04_playlist",
		Name:       "Playlist Management",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q4a_list_check",
		Name:       "List check",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q3_lremove_all",
		Name:       "List Remove All",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q3_shift",
		Name:       "Shift",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q1_sparse",
		Name:       "Sparse Graph",
	},
	{
		CourseCode: "2110211",
		Group:      "d57",
		Code:       "d57_q1_dense",
		Name:       "Dense Graph",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_08_05",
		Name:       "Digital: Simulation 08 - 05",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_08_04",
		Name:       "Digital: Simulation 08 - 04",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_08_03",
		Name:       "Digital: Simulation 08 - 03",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_08_02",
		Name:       "Digital: Simulation 08 - 02",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_08_01",
		Name:       "Digital: Simulation 08 - 01",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q4b_shallowest",
		Name:       "Shallowest Leaf",
	},
	{
		CourseCode: "2110211",
		Group:      "d60",
		Code:       "d60_q3_same_tree",
		Name:       "ต้นไม้เหมือน",
	},
	{
		CourseCode: "2110211",
		Group:      "d63",
		Code:       "d63_q4a_leaves_count",
		Name:       "Leaves Count",
	},
	{
		CourseCode: "2110211",
		Group:      "d64",
		Code:       "d64_q4a_subtree",
		Name:       "Subtree Extract",
	},
	{
		CourseCode: "2110211",
		Group:      "d59",
		Code:       "d59_q3_bst_split",
		Name:       "BST Split",
	},
	{
		CourseCode: "2110211",
		Group:      "d58",
		Code:       "d58_q3_unary",
		Name:       "Count Unary",
	},
	{
		CourseCode: "2110211",
		Group:      "ds",
		Code:       "ds04_best_bst",
		Name:       "Optimal Binary Search Tree",
	},
	{
		CourseCode: "2110211",
		Group:      "d65",
		Code:       "d65_q4a_bst_at_level",
		Name:       "BST at level",
	},
	{
		CourseCode: "2110211",
		Group:      "d61",
		Code:       "d61_q2_imbalance",
		Name:       "Imbalance",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q1c_company_department",
		Name:       "Company Department",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q2b_stack_reverse",
		Name:       "Stack Reverse",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q3a_queue_vertical_split",
		Name:       "Queue Vertical Split",
	},
	{
		CourseCode: "2110211",
		Group:      "d66",
		Code:       "d66_q3a_kheap_check",
		Name:       "K-ary Heap Check",
	},
	{
		CourseCode: "2110263",
		Group:      "diglab",
		Code:       "diglab_09_01",
		Name:       "Digital: Simulation 09 - Vending Machine",
	},
}
